Iter5
shipherman/go-metrics pull request #6
Opened 2023-05-07 16:36 UTC by shipherman

2023-05-08 23:15 UTC, maxlyaptsev requested changes

2023-05-08 23:15 UTC, maxlyaptsev commented on cmd/agent/agent.go
> +    go func() {
использовать горутину в этом задании не требовалось, а если уж использовать - ее нужно правильно реализовать. В данном случае горутина будет работать вечно и ее невозможно остановить, а также нет обработки паники. Кроме этого мапа неконкурентнобезопасна и с этим тоже нужно что-то делать. 

Поэтому предлагаю использовать другой способ контролируемо пройтись. Например для этой задачи очень подходит  https://pkg.go.dev/time#Ticker  - в интернете много написано как его использовать, там ничего сложного

2023-05-08 23:15 UTC, maxlyaptsev commented on cmd/agent/agent.go
> +    if resp.StatusCode != http.StatusOK {
использование клиента из пакета resty делает код гараздо читабельнее и компактней

2023-05-09 13:38 UTC, shipherman commented on cmd/agent/agent.go
> +        req := "http://" + options.serverAddress + "/update/" + mtype + fmt.Sprintf("/%v/%v",k,v)
исправил на strings.Join()

2023-05-09 13:39 UTC, shipherman commented on cmd/agent/agent.go
> +    go func() {
Заменил горутину на time.Tickers

2023-05-09 14:16 UTC, shipherman commented on cmd/agent/agent.go
> +    resp, err := http.PostForm(req, contentType)
Исправил

2023-05-09 14:18 UTC, shipherman commented on cmd/agent/agent.go
> +func SendPostRequest (req string) error {
Сделал методы неимпортируемыми, перенёс в отдельные файлы

2023-05-09 14:18 UTC, shipherman commented on cmd/server/server.go
> +    io.WriteString(w, fmt.Sprintf("%v", v))
Исправил

2023-05-10 12:25 UTC, shipherman commented on cmd/server/server.go
> +func main() {
Разделил

2023-05-10 12:25 UTC, shipherman commented on cmd/server/server.go
> +    //http://<АДРЕС_СЕРВЕРА>/update/<ТИП_МЕТРИКИ>/<ИМЯ_МЕТРИКИ>/<ЗНАЧЕНИЕ_МЕТРИКИ>,
Почистил

2023-05-11 15:55 UTC, closed without merging